{% set version = "0.2.3" %}

package:
  name: jupyter_ydoc
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/j/jupyter_ydoc/jupyter_ydoc-{{ version }}.tar.gz
    sha256: 98db7785215873c64d7dfcb1b741f41df11994c4b3d7e2957e004b392d6f11ea
  - folder: src
    url: https://github.com/jupyter-server/jupyter_ydoc/archive/refs/tags/v{{ version }}.tar.gz
    sha256: fbc990fd64651310290aa994389ebe3d3b596c45f613cbb567184256d304e218

build:
  noarch: python
  number: 0
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-nodejs-version
    - hatchling >=1.10.0
    - pip
    - python >=3.7
  run:
    - importlib_metadata >=3.6
    - python >=3.7
    - y-py >=0.5.3,<0.6.0

test:
  source_files:
    - src/javascript
    - src/package.json
    - src/tests
  requires:
    - pip
    # - nodejs >=18,<19
    # - pytest-asyncio
    # - pytest-cov
    # - websockets >=10.0
    # - yarn <2
    # - ypy-websocket >=0.3.1,<0.4.0
  imports:
    - jupyter_ydoc
  commands:
    - pip check
    # TODO: restore tests: in azure, it pulls an ipv6 address, which the tests aren't expecting
    # - export YARN_CACHE_FOLDER="$SRC_DIR/.yarn-cache"  # [unix]
    # - set YARN_CACHE_FOLDER="%SRC_DIR%/.yarn-cache"  # [win]
    # - cd src/javascript && yarn && yarn build && yarn link --link-folder=../../.yarn-links
    # - cd "$SRC_DIR"  # [unix]
    # - cd "%SRC_DIR%"  # [win]
    # - cd src/tests && yarn && yarn link "@jupyter/ydoc" --link-folder=../../.yarn-links
    # - cd "$SRC_DIR"  # [unix]
    # - cd "%SRC_DIR%"  # [win]
    # - pytest -vv --asyncio-mode=auto --cov=jupyter_ydoc --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=56

about:
  home: https://github.com/jupyter-server/jupyter_ydoc
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE
  summary: Document structures for collaborative editing using Ypy
  doc_url: https://jupyter-ydoc.readthedocs.io

extra:
  recipe-maintainers:
    - davidbrochart
    - conda-forge/jupyter_server
